heat_template_version: 2016-10-14
description: An example template for CCP-EN1 OSTK Lab

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      key_name: 
      image: 
      networks: 
        - port: { get_resource: port }
  port:
    type: OS::Neutron::Port
    properties:
      network: 
      security_groups:
        - default
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network:
  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }

outputs:
  internal_ip:
    description: internal ip address of the server
    value: { get_attr: [server, first_address] }
  public_ip:
    description: floating ip associated with the server
    value: { get_attr: [floating_ip, floating_ip_address] }
