heat_template_version: 2016-10-14
description: An example template for CCP1-EN1 OSTK Lab

resources:
  sshkey:
    type: OS::Nova::KeyPair
    properties:
      name: testkey
      save_private_key: true
  private_network:
    type: OS::Neutron::Net
    properties:
      name: myprivateheatnet
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      cidr: 192.168.0.0/24
      allocation_pools:
        - start: 192.168.0.2
          end: 192.168.0.254
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: external
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }
  port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_network }
      security_groups:
        - default
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: external
  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }
  server:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      key_name: { get_resource: sshkey }
      image: CCP1-EN-OSTK-Lab_ubuntu-16.04-docker-multinic
      networks:
        - port: { get_resource: port }
outputs:
  internal_ip:
    description: internal ip address of the server
    value: { get_attr: [server, first_address] }
  public_ip:
    description: floating ip associated with the server
    value: { get_attr: [floating_ip, floating_ip_address] }
  ssh_public_key:
    description: The public key of the keypair
    value: { get_attr: [sshkey, public_key] }
  ssh_private_key:
    description: The private key of the keypair
    value: { get_attr: [sshkey, private_key] }
