apiVersion: v1
kind: Service
metadata:
  labels:
    component: frontend
  name: frontend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: frontend
  selector:
    app: todo
    component: frontend
  type: NodePort
