apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
    app: todo
spec:
  containers:
    - name: frontend
      image: icclabcna/ccp2-k8s-todo-frontend
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 100m
      env:
        - name: API_ENDPOINT_URL
          value: http://api-svc:8081
          # for value one can also use
          # http://api-svc.default.svc.cluster.local:8081
          # http://{internal IP of API service}:8081
