apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    component: redis
    app: todo
spec:
  containers:
    - name: redis
      image: redis:3.2.10-alpine
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: 100m
      args:
        - redis-server
        - --requirepass ccp2
        - --appendonly yes
